### ISSUE TITLE
Rendering

### ISSUE THREAD

**Issue by joshwa71** [safe-slac/safe-slac#1]
Hi,

Awesome repo and awesome paper.

I'm trying to render some of the agent's runs when running the code, but there seems to be some issue with the PixelObservationWrapper that turns the screen black after the first frame. Any help would be great.

**Comment by safe-slac** [comment]
Hi, thanks for your question. I believe this is a limitation of (this version of) SafetyGym - rendering to a pixel array and to a window in the same environment instance is not supported. If you want to look at the trajectories, you can collect the pixel array observations and save them using e.g. moviepy.

Apologies for the late response; this repo was only intended for the anonymous ICLR submission and is not monitored. We will archive it to reflect that. If you have any questions in the future, please open an issue at https://github.com/lava-lab/safe-slac .

Best, Yannick
